"""
intake_to_contracts.py — deterministically turn a filled intake into the two contracts.

This is CODE, not AI judgement: the agent must not hand-write contracts or infer project
facts from chat memory. Fill intake/<name>_intake.yaml, then:

    python intake/intake_to_contracts.py intake/<name>_intake.yaml [--outdir examples]

Outputs <name>_project.json and <name>_data_structure.json, and validates the project
contract against project_declaration.schema.json. Missing required fields cause a clear
error listing exactly what to fill — so the agent asks instead of guessing.

Deps: pip install pyyaml jsonschema
"""
from __future__ import annotations
import argparse, json, sys
from pathlib import Path
import yaml
from jsonschema import Draft7Validator

ROOT = Path(__file__).resolve().parent.parent
KIT = ROOT / "kit"

REQUIRED = [
    ("project.name", lambda d: d.get("project", {}).get("name")),
    ("project.analyst", lambda d: d.get("project", {}).get("analyst")),
    ("project.date", lambda d: d.get("project", {}).get("date")),
    ("project.domain", lambda d: d.get("project", {}).get("domain")),
    ("objectives", lambda d: d.get("objectives")),
    ("data_collection.methods", lambda d: d.get("data_collection", {}).get("methods")),
    ("data_collection.n_products", lambda d: d.get("data_collection", {}).get("n_products")),
    ("governance.anonymized", lambda d: d.get("governance", {}).get("anonymized") is not None or None),
    ("governance.decision_stakes", lambda d: d.get("governance", {}).get("decision_stakes")),
    ("data.file.path", lambda d: d.get("data", {}).get("file", {}).get("path")),
    ("data.tables", lambda d: d.get("data", {}).get("tables")),
]


def check_required(intake):
    missing = [name for name, get in REQUIRED if not get(intake)]
    if missing:
        print("INTAKE INCOMPLETE — fill these before running analysis:")
        for m in missing:
            print(f"  - {m}")
        sys.exit(2)


def build_project(intake):
    dc = intake.get("data_collection", {})
    return {
        "project": intake["project"],
        "domain": intake["project"]["domain"],
        "business_question": intake.get("business_question", ""),
        "objectives": [
            {"objective_type": o["type"], "primary": bool(o.get("primary", False)),
             **({"description": o["description"]} if o.get("description") else {})}
            for o in intake["objectives"]
        ],
        "data_collection": {k: v for k, v in {
            "methods": dc.get("methods"),
            "presentation_design": dc.get("presentation_design"),
            "balanced_design": dc.get("balanced_design"),
            "replicates": dc.get("replicates"),
            "n_products": dc.get("n_products"),
            "n_consumers": dc.get("n_consumers"),
            "n_panelists": dc.get("n_panelists"),
            "hedonic_scale": dc.get("hedonic_scale"),
            "sampling": dc.get("sampling"),
            "fieldwork_period": dc.get("fieldwork_period"),
            "known_limitations": dc.get("known_limitations", []),
        }.items() if v is not None},
        "governance": intake["governance"],
    }


def build_structure(intake):
    data = intake["data"]
    return {
        "_status": "Generated by intake_to_contracts.py — do not hand-edit; change the intake YAML instead.",
        "file": data["file"],
        "tables": data["tables"],
        **({"group_recodes": data["group_recodes"]} if data.get("group_recodes") else {}),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("intake")
    ap.add_argument("--outdir", default="examples")
    args = ap.parse_args()

    intake = yaml.safe_load(Path(args.intake).read_text(encoding="utf-8"))
    check_required(intake)

    project = build_project(intake)
    structure = build_structure(intake)

    # validate the project contract strictly against the schema
    schema = json.loads((KIT / "project_declaration.schema.json").read_text(encoding="utf-8"))
    errs = sorted(Draft7Validator(schema).iter_errors(project), key=lambda e: list(e.path))
    if errs:
        print("PROJECT CONTRACT INVALID:")
        for e in errs:
            print(f"  - {list(e.path)}: {e.message}")
        sys.exit(3)

    name = Path(args.intake).stem.replace("_intake", "")
    outdir = (ROOT / args.outdir); outdir.mkdir(exist_ok=True)
    pj = outdir / f"{name}_project.json"; ds = outdir / f"{name}_data_structure.json"
    pj.write_text(json.dumps(project, ensure_ascii=False, indent=2), encoding="utf-8")
    ds.write_text(json.dumps(structure, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"OK -> {pj.relative_to(ROOT)}")
    print(f"OK -> {ds.relative_to(ROOT)}")
    print("Project contract validated against schema. Hand these to kit/run_agent.py.")


if __name__ == "__main__":
    sys.exit(main())
